SELECT * FROM sm_doctype

====================================================================================================
Checking of missing doctypes:
====================================================================================================

    SELECT 
            c.fcompanyid, 
            c.fname, 
            GROUP_CONCAT(dt.fdoctype ORDER BY dt.fdoctype) AS missing_doctypes
        FROM 
            sm_company c
        CROSS JOIN (
            SELECT 101 AS fdoctype UNION ALL
            SELECT 102 UNION ALL
            SELECT 103 UNION ALL
            SELECT 104 
        ) AS dt
        LEFT JOIN 
            sm_doctype d ON c.fcompanyid = d.fcompanyid AND dt.fdoctype = d.fdoctype
        WHERE 
            c.factive_flag = '1' AND d.fcompanyid IS NULL
        GROUP BY 
            c.fcompanyid;
====================================================================================================



====================================================================================================
Insertion of missing doctypes:
====================================================================================================
    INSERT INTO `sm_doctype`
        (`fcompanyid`, `fdoctype`, `fname`, `ftrxtype`, `fmemo`, `fcreated_by`, `fcreated_date`, `fupdated_by`, `fupdated_date`, `fcost_flag`,
        `fcheck_inventory_flag`, `fcheck_inventory_lot_flag`, `frequire_lot_flag`, `fedit_price_flag`, `fctm_template_override_flag`, `fctm_template_product_line_count`,
        `fctm_template_print_lot_flag`, `fctm_template_format`, `fallow_barcode_qty`, `fqty_precision`, `fallow_previous_adjust`, `fmanual_receipt_flag`)
        SELECT 
            c.fcompanyid, 
            dt.fdoctype, 
            CASE dt.fdoctype 
                WHEN 101 THEN 'Transfer' 
                WHEN 102 THEN 'Transfer In' 
                WHEN 103 THEN 'Transfer Out' 
                WHEN 104 THEN 'Stock Count'
            ELSE ''
            END AS fname,
            CASE dt.fdoctype 
                WHEN 101 THEN '2' 
                WHEN 102 THEN '0' 
                WHEN 103 THEN '1' 
                WHEN 104 THEN '0'
            ELSE ''
            END AS ftrxtype,
            'Generated by Default' AS fmemo,
            NULL AS fcreated_by,
            NULL AS fcreated_date,
            NULL AS fupdated_by,
            NULL AS fupdated_date,
            '0' AS fcost_flag,
            NULL AS fcheck_inventory_flag,
            NULL AS fcheck_inventory_lot_flag,
            '0' AS frequire_lot_flag,
            NULL AS fedit_price_flag,
            '0' AS fctm_template_override_flag,
            '0' AS fctm_template_product_line_count,
            NULL AS fctm_template_print_lot_flag,
            '0' AS fctm_template_format,
            '0' AS fallow_barcode_qty,
            '1' AS fqty_precision,
            '1' AS fallow_previous_adjust,
            '0' AS fmanual_receipt_flag
        FROM 
            sm_company c
        CROSS JOIN (
            SELECT 101 AS fdoctype UNION ALL
            SELECT 102 UNION ALL
            SELECT 103 UNION ALL
            SELECT 104 
        ) AS dt
        LEFT JOIN 
            sm_doctype d ON c.fcompanyid = d.fcompanyid AND dt.fdoctype = d.fdoctype
        WHERE 
            c.factive_flag = '1' AND d.fcompanyid IS NULL;
====================================================================================================

/*
====================================================================================================
- script

- run stored_procedure

	- cd to 
	C:\wamp64\bin\mysql\mysql5.7.36\bin

	- run command (x2) (local setup db name should be replaced with the actual database name)
	mysql -uroot [db name] --force < D:\www\jacob\appserv\app\batch\stored_procedures.sql
====================================================================================================
*/
